"""
Generate a placeholder app icon for GalEngine Editor.
Creates icon.ico (Windows), icon.icns placeholder (macOS), and icon.png (Linux).

Usage: python scripts/generate-icon.py
Requires: pip install Pillow
"""
import sys
import os

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print("[ERROR] Pillow is required. Install with: pip install Pillow")
    sys.exit(1)

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "resources", "icons")
os.makedirs(OUT_DIR, exist_ok=True)

# --- Configuration ---
SIZES = [16, 24, 32, 48, 64, 128, 256]
BG_COLOR = (30, 30, 30)       # Dark background
ACCENT_COLOR = (110, 168, 254)  # Blue accent
TEXT_COLOR = (255, 255, 255)    # White text


def draw_icon(size: int) -> Image.Image:
    """Draw a simple GE icon (stylized G and E letters)."""
    img = Image.new("RGBA", (size, size), BG_COLOR)
    draw = ImageDraw.Draw(img)

    margin = size // 6
    inner = size - 2 * margin

    # Rounded rectangle background
    draw.rounded_rectangle(
        [margin, margin, margin + inner, margin + inner],
        radius=size // 8,
        fill=ACCENT_COLOR,
    )

    # Try to render "GE" text; fall back to a simple diamond
    try:
        font_size = size // 2
        font = ImageFont.truetype("segoeui.ttf", font_size)
    except (IOError, OSError):
        try:
            font = ImageFont.truetype("arial.ttf", font_size)
        except (IOError, OSError):
            font = ImageFont.load_default()

    bbox = draw.textbbox((0, 0), "GE", font=font)
    tw = bbox[2] - bbox[0]
    th = bbox[3] - bbox[1]
    x = (size - tw) // 2
    y = (size - th) // 2 - size // 16
    draw.text((x, y), "GE", fill=TEXT_COLOR, font=font)

    return img


def main():
    print(f"Generating icons -> {OUT_DIR}")

    # Generate multi-resolution ICO (Windows)
    # Pillow: use the largest image (256x256) as base, sizes param auto-downsamples
    print(f"  Rendering base 256x256...")
    base_img = draw_icon(256)

    ico_path = os.path.join(OUT_DIR, "icon.ico")
    base_img.save(
        ico_path,
        format="ICO",
        sizes=[(s, s) for s in SIZES],
    )
    print(f"  [OK] {ico_path}")

    # Generate PNG (Linux)
    png_path = os.path.join(OUT_DIR, "icon.png")
    img_256 = draw_icon(256)
    img_256.save(png_path, format="PNG")
    print(f"  [OK] {png_path}")

    # Generate placeholder ICNS (macOS — requires actual icns conversion tool)
    # We just save a high-res PNG as a fallback; macOS packaging will need a real icns.
    icns_note = os.path.join(OUT_DIR, "icon.icns.txt")
    with open(icns_note, "w") as f:
        f.write(
            "placeholder — replace with real icon.icns generated by:\n"
            "  iconutil -c icns icon.iconset\n"
            "Or use an online converter from icon.png\n"
        )
    print(f"  [NOTE] macOS icon.icns requires manual conversion — see {icns_note}")

    print("\nDone! Icon files generated.")


if __name__ == "__main__":
    main()
